[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "manager"
version = "0.0.2"
dependencies = [
    "Flask==3.0.3",
]

[tool.setuptools.packages.find]
where = ["manager"]  
exclude = [ "bin" ]
