name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
          checkName: 'check'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        python -m pytest --ctrf ctrf-report.json --cov-report xml:coverage.xml

    - name: Publish Test Summary Results
      run: npx github-actions-ctrf ctrf-report.json

    - name: Get Cover 
      uses: orgoro/coverage@v3.2
      with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}


